/*
 * Rekor
 *
 * Rekor is a cryptographically secure, immutable transparency log for signed software releases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use crate::models::log_entry_value::{Hash, Signature};


#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HashedRekordObj {
    pub data: HashRekordData,
    pub signature: Signature,
}


#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HashRekordData {
    pub hash: Hash,
}


