/*
 * Rekor
 *
 * Rekor is a cryptographically secure, immutable transparency log for signed software releases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

#[cfg(feature = "no_std")]
use alloc::string::String;



#[cfg(feature = "std")]
use HashMap as Map;
use crate::models::log_entry_value::{Hash, PublicKey};


#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HelmObj {
    pub public_key: PublicKey,
    pub chart: HelmChart,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HelmChart {
    pub hash: Hash,
    pub provenance: Provenance,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Provenance {
    pub signature: ProvenanceSignature,
    pub content: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProvenanceSignature {
    pub content: String,
}


