/*
 * Rekor
 *
 * Rekor is a cryptographically secure, immutable transparency log for signed software releases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LogEntryValueVerification {
    #[serde(rename = "inclusionProof", skip_serializing_if = "Option::is_none")]
    pub inclusion_proof: Option<alloc::boxed::Box<crate::models::InclusionProof>>,
    /// Signature over the logID, logIndex, body and integratedTime.
    #[serde(rename = "signedEntryTimestamp", skip_serializing_if = "Option::is_none")]
    pub signed_entry_timestamp: Option<alloc::string::String>,
}

impl LogEntryValueVerification {
    pub fn new() -> LogEntryValueVerification {
        LogEntryValueVerification {
            inclusion_proof: Option::<_>::None,
            signed_entry_timestamp: Option::<_>::None,
        }
    }
}


