/*
 * Rekor
 *
 * Rekor is a cryptographically secure, immutable transparency log for signed software releases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[cfg(feature = "no_std")]
use alloc::string::String;



#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all="camelCase")]
pub struct SearchIndexPublicKey {
    #[serde(rename = "format")]
    pub format: Format,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl SearchIndexPublicKey {
    pub fn new(format: Format) -> SearchIndexPublicKey {
        SearchIndexPublicKey {
            format,
            content: Option::<_>::None,
            url: Option::<_>::None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, serde::Serialize, serde::Deserialize)]
#[serde(rename_all="camelCase")]
pub enum Format {
    Pgp,
    X509,
    Minisign,
    Ssh,
    Tuf,
}

impl Default for Format {
    fn default() -> Format {
        Self::Pgp
    }
}

