/*
 * Rekor
 *
 * Rekor is a cryptographically secure, immutable transparency log for signed software releases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

#[cfg(feature = "no_std")]
use alloc::string::String;

#[cfg(feature = "no_std")]
use alloc::collections::BTreeMap as Map;

#[cfg(feature = "std")]
use HashMap as Map;


#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TufObj {
    #[serde(rename = "snake_case")] //https://github.com/sigstore/rekor/blob/ee83776f8b3b3c44829521d36472f4cac5c81f4d/pkg/types/tuf/v0.0.1/tuf_v0_0_1_schema.json#L8
    pub spec_version: String,
    pub metadata: TufMetaData,
    pub root: TufRoot,
}

pub type TufRoot = Map<String, String>;
pub type TufMetaData = Map<String, String>;



